### ISSUE TITLE
comentarios avances 2

### ISSUE THREAD

**Issue by AliciaMstt** [GissellaPineda/Proyec_Final_Bioinfo_2017_II#2]
Pintan bien tus avances. Sólo por favor menciona con qué harás el procesamiento de los datos y asegúrate de no tener problemas con el software al respecto.

**Comment by GissellaPineda** [comment]
El procesamiento lo voy a hacer con ipyrad, no he tenido problemas con la instalación de ese programa.

**Comment by GissellaPineda** [comment]
Hola!
Tuve un problema, resulta que estuve haciendo trimming y filtrado pero las secuencias se veian muy mal, terribles, algo no estaba bien, me puse a revisar todos los pasos que había hecho y encontré que en los parametros que le puse a ipyrad para el demultipexig estaba mal un path, al correrlo no me mostró error, pero me di cuenta que me cortó las secuencias muchisimo y quedaron super pequeñitas y extrañas, por eso los filtros me salian tan raros. Debido a esto volví a iniciar de cero, ya está corriendo de nuevo, pero al parecer el demultiplexing se va a tardar bastante tiempo porque el archivo es muy grande. Lo estoy haciendo en el sevidor de Ella Vazquez, pero hay varias cosas corriendo ahí, así que se demorará un poco. Mientras tanto sólo estoy leyendo, porque no puedo avanzar.

**Comment by AliciaMstt** [comment]
Está bien, qué bueno que te diste cuenta. Así es la bioinformática. Intenta ir planeando qué harás después y ir generando tus scripts con datos de chocolate (los programas normalmente traen datos prueba) o de Dryad para los pasos subsecuentes. Así ya namás sería correrlo con lo tuyo.
